version: 2
updates:
  - package-ecosystem: docker
    directory: "/playground/.devops"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/projeto-gerar-horario"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: "/projeto-gerar-horario/.devops/dotnet-sdk"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
