version: 2
updates:
  - package-ecosystem: docker
    directory: "/playground/_devops"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/projeto-gerar-horario"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
