FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App
# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore Microsservicos/GerarHorario-Service
# Build and publish a release
RUN dotnet publish Microsservicos/GerarHorario-Service -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0



WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "GerarHorario-Service.dll"]
