name: Runs tests of estudo-node-z3

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest

    # permissions:
    #   # Required to checkout the code
    #   contents: read
    #   # Required to put a comment into the pull-request
    #   pull-requests: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: 'Test'
        working-directory: ./estudo-node-z3/projeto
        run: npm run coverage
      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        with:
          working-directory: ./estudo-node-z3/projeto
        uses:  davelosert/vitest-coverage-report-action@v2
